hunav_loader:
  ros__parameters:
    map: open_area
    publish_people: true
    agents: [walker1, walker2, walker3, walker4, walker5, walker6, walker7, walker8]
    walker1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 1.0
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.75, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 2.0, y: -2.5, z: 1.25, h: 1.5708}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 2.0, y: 2.5, h: 1.5708}
      g1: {x: 2.0, y: -2.5, h: -1.5708}
    walker2:
      id: 2
      skin: 1
      group_id: -1
      max_vel: 0.9
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.7, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 3.0, y: 2.5, z: 1.25, h: -1.5708}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 3.0, y: -2.5, h: -1.5708}
      g1: {x: 3.0, y: 2.5, h: 1.5708}
    walker3:
      id: 3
      skin: 2
      group_id: -1
      max_vel: 1.0
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.8, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 4.0, y: -2.5, z: 1.25, h: 1.5708}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 4.0, y: 2.5, h: 1.5708}
      g1: {x: 4.0, y: -2.5, h: -1.5708}
    walker4:
      id: 4
      skin: 3
      group_id: -1
      max_vel: 0.9
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.7, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 5.0, y: 2.5, z: 1.25, h: -1.5708}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 5.0, y: -2.5, h: -1.5708}
      g1: {x: 5.0, y: 2.5, h: 1.5708}
    walker5:
      id: 5
      skin: 4
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.65, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 7.0, y: 0.7, z: 1.25, h: 3.14159}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 1.0, y: 0.7, h: 3.14159}
      g1: {x: 7.0, y: 0.7, h: 0.0}
    walker6:
      id: 6
      skin: 0
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.65, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 1.0, y: -0.8, z: 1.25, h: 0.0}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 7.0, y: -0.8, h: 0.0}
      g1: {x: 1.0, y: -0.8, h: 3.14159}
    walker7:
      id: 7
      skin: 1
      group_id: -1
      max_vel: 0.9
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.7, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 6.0, y: -2.5, z: 1.25, h: 1.5708}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 6.0, y: 2.5, h: 1.5708}
      g1: {x: 6.0, y: -2.5, h: -1.5708}
    walker8:
      id: 8
      skin: 2
      group_id: -1
      max_vel: 0.9
      radius: 0.4
      behavior: {type: 1, configuration: 1, duration: 120.0, once: true, vel: 0.7, dist: 0.0, goal_force_factor: 2.0, obstacle_force_factor: 10.0, social_force_factor: 5.0, other_force_factor: 20.0}
      init_pose: {x: 7.0, y: 2.5, z: 1.25, h: -1.5708}
      goal_radius: 0.3
      cyclic_goals: true
      goals: [g0, g1]
      g0: {x: 7.0, y: -2.5, h: -1.5708}
      g1: {x: 7.0, y: 2.5, h: 1.5708}
